# Generated by Django 4.2.2 on 2023-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(blank=True, choices=[('dogs', 'Dogs'), ('cats', 'Cats'), ('dadj', "Dad's Jokes"), ('other', 'Other')], max_length=50),
        ),
    ]
