# Generated by Django 4.2.2 on 2023-12-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
