# Generated by Django 4.2.2 on 2023-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newsstory_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
