# Generated by Django 4.2.2 on 2023-12-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsstory_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='date_updated',
        ),
    ]
