# Generated by Django 4.2.2 on 2023-12-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newsstory_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
