# Generated by Django 4.2.2 on 2023-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(blank=True, choices=[('dogs', 'Dogs'), ('cats', 'Cats'), ('motorbikes', 'Motorbikes'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
