# Generated by Django 4.2.2 on 2023-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsstory_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='update_date',
            field=models.DateTimeField(verbose_name='Date updated'),
        ),
    ]
