# Generated by Django 4.2.2 on 2023-12-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_newsstory_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
