# Generated by Django 4.2.2 on 2023-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_newsstory_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='Update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
