# Generated by Django 4.2.2 on 2023-12-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_update_date_newsstory_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='last_update',
            new_name='update_date',
        ),
    ]
