# Generated by Django 4.2.2 on 2023-12-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_rename_last_update_newsstory_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='update_date',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
