# Generated by Django 4.2.2 on 2023-12-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_remove_newsstory_update_date_newsstory_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='last_update',
        ),
    ]
